//------------------------------------------------------------------------------
// <autogenerated>
//   This file was generated by T4 code generator ProductModel.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using NTier.Common.Domain.Model;
using NTier.Server.Domain.Repositories;
using ProductManager.Common.Domain.Model.ProductManager;

namespace ProductManager.Server.Domain.Repositories
{
    public partial class ProductManagerRepository : NTier.Server.Domain.Repositories.EntityFramework.Repository, IProductManagerRepository
    {
        #region Constructors

        public ProductManagerRepository()
            : base("name=ProductManagerEntities", "ProductManagerEntities")
        {
        }

        public ProductManagerRepository(string connectionString, string containerName = "ProductManagerEntities")
            : base(connectionString, containerName)
        {
        }

        public ProductManagerRepository(EntityConnection connection, string containerName = "ProductManagerEntities")
            : base(connection, containerName)
        {
        }

        #endregion Constructors

        #region EntitySets

        public IEntitySet<Product> Products
        {
            get { return _products  ?? (_products = CreateEntitySet<Product>("Products")); }
        }
        private IEntitySet<Product> _products;

        public IEntitySet<ProductCategory> ProductCategories
        {
            get { return _productCategories  ?? (_productCategories = CreateEntitySet<ProductCategory>("ProductCategories")); }
        }
        private IEntitySet<ProductCategory> _productCategories;

        #endregion EntitySets
    }
}
