//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator ProductModel.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.Composition;
using System.ComponentModel.Composition.Hosting;
using System.Linq;
using System.ServiceModel;
using System.Transactions;
using NTier.Client.Domain;
using NTier.Client.Domain.Service.ChannelFactory;
using NTier.Common.Domain.Model;
using ProductManager.Common.Domain.Model.ProductManager;
using ProductManager.Common.Domain.Service.Contracts;

namespace ProductManager.Client.Domain
{
    public sealed partial class ProductManagerDataContext : DataContext<ProductManagerResultSet>, IProductManagerDataContext
    {
        #region Fields

        private readonly Func<IProductManagerDataService> _dataServiceFactory;

        private readonly Func<IProductManagerChangeSetFactory> _changeSetFactoryProvider;

        private readonly InternalEntitySet<Product> _products;
        private readonly InternalEntitySet<ProductCategory> _productCategories;
 
        private IEntitySet<Product> productEntitySet;
        private IEntitySet<ProductCategory> productCategoryEntitySet;

        #endregion Fields

        #region Contructor

        partial void Initialize();

        public ProductManagerDataContext(Func<IProductManagerDataService> dataServiceFactory, Func<IProductManagerChangeSetFactory> changeSetFactoryProvider = null)
        {
            _dataServiceFactory = dataServiceFactory;

            _changeSetFactoryProvider = changeSetFactoryProvider ?? (() => new ProductManagerChangeSetFactory());

            _products = CreateAndRegisterInternalEntitySet<Product>();
            _productCategories = CreateAndRegisterInternalEntitySet<ProductCategory>();

            Initialize();
        }

        public ProductManagerDataContext(IChannelFactory<IProductManagerDataService> channelFactory, Func<IProductManagerChangeSetFactory> changeSetFactoryProvider = null)
            : this(channelFactory.CreateChannel, changeSetFactoryProvider)
        {
        }

        public ProductManagerDataContext(string endpointConfigurationName = "ProductManagerDataService", Func<IProductManagerChangeSetFactory> changeSetFactoryProvider = null)
            : this(CreateChannelFactory(endpointConfigurationName).CreateChannel, changeSetFactoryProvider)
        {
        }

        private static ChannelFactory<IProductManagerDataService> CreateChannelFactory(string endpointConfigurationName)
        {
            var channelFactory = string.IsNullOrEmpty(endpointConfigurationName)
                ? new ChannelFactory<IProductManagerDataService>()
                : new ChannelFactory<IProductManagerDataService>(endpointConfigurationName);
            return channelFactory;
        }

        #endregion Contructor

        #region Entities

        #region Products

        public IEntitySet<Product> Products
        {
            get
            {
                if (ReferenceEquals(null, productEntitySet))
                {
                    productEntitySet = CreateEntitySet<Product>(_products, AttachWithRelations, OnDetach, GetProducts);
                }

                return productEntitySet;
            }
        }

        public void Add(Product entity)
        {
            Products.Add(entity);
        }

        public void Delete(Product entity)
        {
            Products.Delete(entity);
        }

        public void Attach(Product entity)
        {
            Products.Attach(entity);
        }

        public void AttachAsModified(Product entity, Product original)
        {
            Products.AttachAsModified(entity, original);
        }

        public void Detach(Product entity)
        {
            Products.Detach(entity);
        }

        private QueryResult<Product> GetProducts(ClientInfo clientInfo, Query query)
        {
            var service = _dataServiceFactory();
            try
            {
                var result = service.GetProducts(clientInfo, query);
                return result;
            }
            finally
            {
                var client = service as ICommunicationObject;
                if (client != null)
                {
                    if (client.State == CommunicationState.Faulted)
                    {
                        client.Abort();
                    }
                    else
                    {
                        client.Close();
                    }
                }
            }
        }

        private Product AttachWithRelations(Product entity, InsertMode insertMode = InsertMode.Attach, MergeOption mergeOption = MergeOption.AppendOnly, List<object> referenceTrackingList = null)
        {
            #region iteration tracking

            if (ReferenceEquals(null, referenceTrackingList))
            {
                referenceTrackingList = new List<object>();
            }

            if (referenceTrackingList.Contains(entity))
            {
                return _products.GetExisting(entity);
            }
            else
            {
                referenceTrackingList.Add(entity);
            }

            #endregion

            #region add/attach entity

            Product existingEntity = null;

            switch (insertMode)
            {
                case InsertMode.Add:
                    existingEntity = _products.Add(entity);
                    break;
                case InsertMode.Attach:
                    existingEntity = _products.Attach(entity);
                    break;
                default:
                    throw new Exception(string.Format("Implementation Exception: missing action for {0}", insertMode));
            }

            if (!ReferenceEquals(null, existingEntity) && ReferenceEquals(existingEntity, entity))
            {
                return existingEntity;
            }

            #endregion

            #region attach relations recursively
            
            // register entity's property changed event if entity is new to context
            if (ReferenceEquals(null, existingEntity))
            {
                entity.PropertyChanged += On_product_propertyChanged;
            }

            // attach related entity to context
            if (!ReferenceEquals(null, entity.ProductCategory))
            {
                var existingRelatedEntity = AttachWithRelations(entity.ProductCategory, insertMode, mergeOption, referenceTrackingList);
            }

            #endregion

            #region refresh existing entity based on merge options

            if (!ReferenceEquals(null, existingEntity) && !ReferenceEquals(existingEntity, entity))
            {
                if (Products.MergeOption == MergeOption.OverwriteChanges)
                {
                    Invoke(delegate
                    {
                        existingEntity.Refresh(entity, trackChanges: false);
                        existingEntity.AcceptChanges();
                    });
                }
                else if (Products.MergeOption == MergeOption.PreserveChanges)
                {
                    Invoke(delegate
                    {
                        existingEntity.Refresh(entity, trackChanges: false, preserveExistingChanges: true);
                    });
                }
            }

            #endregion

            return existingEntity;
        }

        private void OnDetach(Product entity)
        {
            entity.PropertyChanged -= On_product_propertyChanged;

        }

        private void On_product_propertyChanged(object sender, PropertyChangedEventArgs e)
        {
            var entity = sender as Product;
            if (!ReferenceEquals(null, entity) && entity.IsChangeTrackingPrevented)
            {
                return;
            }

            if (e.PropertyName == "ProductCategory")
            {
                var relation = entity[e.PropertyName] as ProductCategory;
                if (!ReferenceEquals(null, relation))
                {
                    Attach(relation);
                }
            }
        }

        #endregion Products

        #region ProductCategories

        public IEntitySet<ProductCategory> ProductCategories
        {
            get
            {
                if (ReferenceEquals(null, productCategoryEntitySet))
                {
                    productCategoryEntitySet = CreateEntitySet<ProductCategory>(_productCategories, AttachWithRelations, OnDetach, GetProductCategories);
                }

                return productCategoryEntitySet;
            }
        }

        public void Add(ProductCategory entity)
        {
            ProductCategories.Add(entity);
        }

        public void Delete(ProductCategory entity)
        {
            ProductCategories.Delete(entity);
        }

        public void Attach(ProductCategory entity)
        {
            ProductCategories.Attach(entity);
        }

        public void AttachAsModified(ProductCategory entity, ProductCategory original)
        {
            ProductCategories.AttachAsModified(entity, original);
        }

        public void Detach(ProductCategory entity)
        {
            ProductCategories.Detach(entity);
        }

        private QueryResult<ProductCategory> GetProductCategories(ClientInfo clientInfo, Query query)
        {
            var service = _dataServiceFactory();
            try
            {
                var result = service.GetProductCategories(clientInfo, query);
                return result;
            }
            finally
            {
                var client = service as ICommunicationObject;
                if (client != null)
                {
                    if (client.State == CommunicationState.Faulted)
                    {
                        client.Abort();
                    }
                    else
                    {
                        client.Close();
                    }
                }
            }
        }

        private ProductCategory AttachWithRelations(ProductCategory entity, InsertMode insertMode = InsertMode.Attach, MergeOption mergeOption = MergeOption.AppendOnly, List<object> referenceTrackingList = null)
        {
            #region iteration tracking

            if (ReferenceEquals(null, referenceTrackingList))
            {
                referenceTrackingList = new List<object>();
            }

            if (referenceTrackingList.Contains(entity))
            {
                return _productCategories.GetExisting(entity);
            }
            else
            {
                referenceTrackingList.Add(entity);
            }

            #endregion

            #region add/attach entity

            ProductCategory existingEntity = null;

            switch (insertMode)
            {
                case InsertMode.Add:
                    existingEntity = _productCategories.Add(entity);
                    break;
                case InsertMode.Attach:
                    existingEntity = _productCategories.Attach(entity);
                    break;
                default:
                    throw new Exception(string.Format("Implementation Exception: missing action for {0}", insertMode));
            }

            if (!ReferenceEquals(null, existingEntity) && ReferenceEquals(existingEntity, entity))
            {
                return existingEntity;
            }

            #endregion

            #region attach relations recursively
            
            // register entity's property changed event if entity is new to context
            if (ReferenceEquals(null, existingEntity))
            {
                entity.PropertyChanged += On_productCategory_propertyChanged;
            }

            if (!ReferenceEquals(null, entity.ChildCategories))
            {
                // register relation's collection changed event if entity is new to context
                if (ReferenceEquals(null, existingEntity))
                {
                    entity.ChildCategories.CollectionChanged += On_productCategory_childCategories_collectionChanged;
                }

                // attach related entities to context
                if (entity.ChildCategories.Count > 0)
                {
                    foreach (var item in entity.ChildCategories.ToArray())
                    {
                        var existingRelatedEntity = AttachWithRelations(item, insertMode, mergeOption, referenceTrackingList);

                        // update relation if entity is new to context or relation is new to entity
                        if (ReferenceEquals(null, existingEntity) || !existingEntity.ChildCategories.Contains(item))
                        {
                            if (!ReferenceEquals(null, existingRelatedEntity) && !ReferenceEquals(existingRelatedEntity, item))
                            {
                                // check merge options
                                if (!(mergeOption == MergeOption.PreserveChanges && existingRelatedEntity.ChangeTracker.OriginalValues.ContainsKey("ParentCategory")))
                                {
                                    using (entity.ChangeTrackingPrevention())
                                    {
                                        entity.ChildCategories.Replace(item, existingRelatedEntity);
                                    }

                                    using (existingRelatedEntity.ChangeTrackingPrevention())
                                    {
                                        existingRelatedEntity.ParentCategory = entity;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // attach related entity to context
            if (!ReferenceEquals(null, entity.ParentCategory))
            {
                var existingRelatedEntity = AttachWithRelations(entity.ParentCategory, insertMode, mergeOption, referenceTrackingList);

                // update relation if entity is new to context or relation is new to entity
                if (ReferenceEquals(null, existingEntity) || !entity.ParentCategory.Equals(existingEntity.ParentCategory))
                {
                    if (!ReferenceEquals(null, existingRelatedEntity) && !ReferenceEquals(existingRelatedEntity, entity.ParentCategory))
                    {
                        // check merge options
                        if (!(mergeOption == MergeOption.PreserveChanges && existingRelatedEntity.ChangeTracker.OriginalValues.ContainsKey("ChildCategories")))
                        {
                            using (entity.ChangeTrackingPrevention())
                            {
                                entity.ParentCategory = existingRelatedEntity;
                            }

                            using (existingRelatedEntity.ChangeTrackingPrevention())
                            {
                                var entityToReplace = existingRelatedEntity.ChildCategories.FirstOrDefault(e => e.Equals(entity));
                                if (!ReferenceEquals(null, entityToReplace))
                                {
                                    using (entityToReplace.ChangeTrackingPrevention())
                                    {
                                        existingRelatedEntity.ChildCategories.Remove(entityToReplace);
                                    }
                                }

                                existingRelatedEntity.ChildCategories.Add(entity);
                            }
                        }
                    }
                }
            }

            #endregion

            #region refresh existing entity based on merge options

            if (!ReferenceEquals(null, existingEntity) && !ReferenceEquals(existingEntity, entity))
            {
                if (ProductCategories.MergeOption == MergeOption.OverwriteChanges)
                {
                    Invoke(delegate
                    {
                        existingEntity.Refresh(entity, trackChanges: false);
                        existingEntity.AcceptChanges();
                    });
                }
                else if (ProductCategories.MergeOption == MergeOption.PreserveChanges)
                {
                    Invoke(delegate
                    {
                        existingEntity.Refresh(entity, trackChanges: false, preserveExistingChanges: true);
                    });
                }
            }

            #endregion

            return existingEntity;
        }

        private void OnDetach(ProductCategory entity)
        {
            entity.PropertyChanged -= On_productCategory_propertyChanged;

            if (!ReferenceEquals(null, entity.ChildCategories))
            {
                entity.ChildCategories.CollectionChanged -= On_productCategory_childCategories_collectionChanged;
            }

        }

        private void On_productCategory_propertyChanged(object sender, PropertyChangedEventArgs e)
        {
            var entity = sender as ProductCategory;
            if (!ReferenceEquals(null, entity) && entity.IsChangeTrackingPrevented)
            {
                return;
            }

            if (e.PropertyName == "ParentCategory")
            {
                var relation = entity[e.PropertyName] as ProductCategory;
                if (!ReferenceEquals(null, relation))
                {
                    Attach(relation);
                }
            }
        }

        private void On_productCategory_childCategories_collectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            var entity = sender as ProductCategory;
            if (!ReferenceEquals(null, entity) && entity.IsChangeTrackingPrevented)
            {
                return;
            }

            if (!ReferenceEquals(null, e.NewItems))
            {
                foreach (ProductCategory item in e.NewItems)
                {
                    Attach(item);
                }
            }
        }

        #endregion ProductCategories

        #endregion Entities

        #region Submit Changes

        protected override ProductManagerResultSet SubmitChanges(ClientInfo clientInfo)
        {
            // get reduced change set
            var changeSet = GetChangeSet();

            if (!changeSet.IsEmpty)
            {
                var service = _dataServiceFactory();
                try
                {
                    // submit data
                    var resultSet = service.SubmitChanges(clientInfo, changeSet);
                    return resultSet;
                }
                finally
                {
                    var client = service as ICommunicationObject;
                    if (client != null)
                    {
                        if (client.State == CommunicationState.Faulted)
                        {
                            client.Abort();
                        }
                        else
                        {
                            client.Close();
                        }
                    }
                }
            }
            else
            {
                // return empty result set
                return new ProductManagerResultSet(changeSet);
            }
        }

        private ProductManagerChangeSet GetChangeSet()
        {
            IEnumerable<Product> products;
            lock (_products.SyncRoot)
            {
                products = _products.GetAllEntities();
            }

            IEnumerable<ProductCategory> productCategories;
            lock (_productCategories.SyncRoot)
            {
                productCategories = _productCategories.GetAllEntities();
            }

            // get reduced change set
            var changeSet = _changeSetFactoryProvider().CreateChangeSet(
                products, 
                productCategories);

            return changeSet;
        }

        protected override void Refresh(ProductManagerResultSet resultSet)
        {
            lock (_products.SyncRoot)
            {
                Refresh(_products, resultSet.Products);
            }

            lock (_productCategories.SyncRoot)
            {
                Refresh(_productCategories, resultSet.ProductCategories);
            }

        }

        #endregion Submit Changes
    }
}
