//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator ProductModel.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using NTier.Client.Domain;
using ProductManager.Common.Domain.Model.ProductManager;

namespace ProductManager.Client.Domain
{
    public partial class ProductManagerChangeSetFactory : ChangeSetFactory, IProductManagerChangeSetFactory
    {
        public ProductManagerChangeSet CreateChangeSet(IEnumerable<Product> products, IEnumerable<ProductCategory> productCategories)
        {
            // retrieve changes sets (modified entities)
            var productChangeSet = GetChangeSet(products);
            var productCategoryChangeSet = GetChangeSet(productCategories);

            // reduce entities (copy changed values)
            var productsMap = ReduceToModifications(productChangeSet);
            var productCategoriesMap = ReduceToModifications(productCategoryChangeSet);

            // fixup relations (replaces related entities with reduced entites)
            FixupRelations(
                CastToEntityTuple(productsMap), 
                CastToEntityTuple(productCategoriesMap)
            );

            var changeSet = new ProductManagerChangeSet();

            if (productsMap.Count > 0) changeSet.Products = productsMap.Select(e => e.ReducedEntity).ToList();
            if (productCategoriesMap.Count > 0) changeSet.ProductCategories = productCategoriesMap.Select(e => e.ReducedEntity).ToList();

            return changeSet;
        }
    }
}
