//------------------------------------------------------------------------------
// <initially_autogenerated>
//   This file was originally generated by T4 code generator Northwind.tt.
//   This file is meant to be edited manually and modifications do not get lost on regeneration.
//   In case you want this file to be deleted or regenerated you have to remove (e.g. delete or rename) the existing version manually.
// </initially_autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using NTier.Common.Domain.Model;

namespace IntegrationTest.Common.Domain.Model.Northwind
{
    [MetadataType(typeof(EmployeeMetadata))]
    partial class Employee
    {
    }

    // This class allows you to attach custom attributes to properties of the Employee class.
    //
    // For example, the following marks the Xyz property as a
    // required property and specifies the format for valid values:
    //    [Required]
    //    [RegularExpression("[A-Z][A-Za-z0-9]*")]
    //    [StringLength(32)]
    //    string Xyz;
    public sealed class EmployeeMetadata
    {
        // this class is not meant to be instantiated by client code
        private EmployeeMetadata() { }

#pragma warning disable 0169

        #region Simple Properties

        public global::System.Int32 EmployeeID;

        public global::System.String LastName;

        public global::System.String FirstName;

        public global::System.String Title;

        public global::System.String TitleOfCourtesy;

        public Nullable<global::System.DateTime> BirthDate;

        public Nullable<global::System.DateTime> HireDate;

        public global::System.String Address;

        public global::System.String City;

        public global::System.String Region;

        public global::System.String PostalCode;

        public global::System.String Country;

        public global::System.String HomePhone;

        public global::System.String Extension;

        public global::System.Byte[] Photo;

        public global::System.String Notes;

        public Nullable<global::System.Int32> ReportsTo;

        public global::System.String PhotoPath;

        #endregion Simple Properties

        #region Complex Properties

        #endregion Complex Properties

        #region Navigation Properties

        public TrackableCollection<Employee> Employees1;

        public Employee Employee1;

        public TrackableCollection<Order> Orders;

        public TrackableCollection<Territory> Territories;

        #endregion Navigation Properties

#pragma warning restore 0169
    }
}
