//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Northwind.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace IntegrationTest.Common.Domain.Model.Northwind
{
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(Territory))]
    public partial class Region : Entity, INotifyPropertyChanged, INotifyPropertyChanging, IDataErrorInfo
    {
        #region Constructor and Initialization

        // partial method for initialization
        partial void Initialize();

        public Region()
        {
            Initialize();
        }

        #endregion Constructor and Initialization

        #region Simple Properties

        [DataMember]
        [Key]
        [Required]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [SimpleProperty]
        public global::System.Int32 RegionID
        {
            get { return _regionID; }
            set
            {
                if (_regionID != value)
                {
                    if (!IsDeserializing && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'RegionID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    RegionIDChanging(value);
                    OnPropertyChanging("RegionID", value);
                    var previousValue = _regionID;
                    _regionID = value;
                    OnPropertyChanged("RegionID", previousValue, value);
                    RegionIDChanged(previousValue);
                }
            }
        }
        private global::System.Int32 _regionID;

        partial void RegionIDChanging(global::System.Int32 newValue);
        partial void RegionIDChanged(global::System.Int32 previousValue);

        [DataMember]
        [Required]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [SimpleProperty]
        public global::System.String RegionDescription
        {
            get { return _regionDescription; }
            set
            {
                if (_regionDescription != value)
                {
                    RegionDescriptionChanging(value);
                    OnPropertyChanging("RegionDescription", value);
                    var previousValue = _regionDescription;
                    _regionDescription = value;
                    OnPropertyChanged("RegionDescription", previousValue, value);
                    RegionDescriptionChanged(previousValue);
                }
            }
        }
        private global::System.String _regionDescription;

        partial void RegionDescriptionChanging(global::System.String newValue);
        partial void RegionDescriptionChanged(global::System.String previousValue);

        #endregion Simple Properties

        #region Complex Properties

        #endregion Complex Properties

        #region Navigation Properties

        [DataMember]
        [NavigationProperty]
        public TrackableCollection<Territory> Territories
        {
            get
            {
                if (_territories == null)
                {
                    _territories = new TrackableCollection<Territory>();
                    _territories.CollectionChanged += FixupTerritories;
                }
                return _territories;
            }
            set
            {
                if (!ReferenceEquals(_territories, value))
                {
                    if (!IsDeserializing && ChangeTracker.IsChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }

                    if (_territories != null)
                    {
                       _territories.CollectionChanged -= FixupTerritories;
                    }

                    _territories = value;

                    if (_territories != null)
                    {
                        _territories.CollectionChanged += FixupTerritories;
                    }

                    OnPropertyChanged("Territories", trackInChangeTracker: false);
                }
            }
        }
        private TrackableCollection<Territory> _territories;

        #endregion Navigation Properties

        #region ChangeTracking

        protected override void ClearNavigationProperties()
        {
            Territories.Clear();
        }

        #endregion ChangeTracking

        #region Association Fixup

        private void FixupTerritories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }

            if (e.NewItems != null)
            {
                foreach (Territory item in e.NewItems)
                {
                    item.Region = this;
                    if (ChangeTracker.IsChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.IsChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        RecordAdditionToCollectionProperties("Territories", item);
                    }
                }
            }

            if (e.OldItems != null)
            {
                foreach (Territory item in e.OldItems)
                {
                    if (ReferenceEquals(item.Region, this))
                    {
                        item.Region = null;
                    }
                    if (ChangeTracker.IsChangeTrackingEnabled)
                    {
                        RecordRemovalFromCollectionProperties("Territories", item);
                    }
                }
            }
        }

        #endregion Association Fixup

        protected override bool IsKeyEqual(Entity other)
        {
            var entity = other as Region;
            if (ReferenceEquals(null, entity)) return false;
            return this.RegionID == entity.RegionID;
        }

        protected override int GetKeyHashCode()
        {
            return this.RegionID.GetHashCode();
        }
    }
}
