//------------------------------------------------------------------------------
// <autogenerated>
//   This file was originally generated by T4 code generator NorthwindModel.tt.
//   This file is meant to be edited manually and modifications do not get lost on regeneration.
//   In case you want this file to be deleted or regenerated you have to remove (e.g. delete or rename) the existing version manually.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace IntegrationTest.Common.Domain.Model.Northwind
{
    [MetadataType(typeof(ContactMetadata))]
    partial class Contact
    {
    }

    // This class allows you to attach custom attributes to properties of the Contact class.
    //
    // For example, the following marks the Xyz property as a
    // required property and specifies the format for valid values:
    //    [Required]
    //    [RegularExpression("[A-Z][A-Za-z0-9]*")]
    //    [StringLength(32)]
    //    string Xyz;
    public sealed class ContactMetadata
    {
        // this class is not meant to be instantiated by client code
        private ContactMetadata() { }

#pragma warning disable 0169

        #region Primitive Properties

        public string Name;    

        public string Title;    

        public string Address;    

        public string City;    

        public string Region;    

        public string PostalCode;    

        public string Country;    

        public string Phone;    

        public string Fax;    

        #endregion Primitive Properties

        #region Complex Properties

        #endregion Complex Properties
        
#pragma warning restore 0169
    }
}
