//------------------------------------------------------------------------------
// <autogenerated>
//   This file was originally generated by T4 code generator NorthwindModel.tt. 
//   This file is meant to be edited manually and modifications do not get lost on regeneration. 
//   In case you want this file to be deleted or regenerated you have to remove (e.g. delete or rename) the existing version manually.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using NTier.Common.Domain.Model;

namespace IntegrationTest.Common.Domain.Model.Northwind
{
    [MetadataType(typeof(EmployeeMetadata))]
    public partial class Employee
    {
    }
    
    // This class allows you to attach custom attributes to properties of the Employee class.
    //
    // For example, the following marks the Xyz property as a
    // required property and specifies the format for valid values:
    //    [Required]
    //    [RegularExpression("[A-Z][A-Za-z0-9]*")]
    //    [StringLength(32)]
    //    string Xyz;
    public sealed class EmployeeMetadata
    {
        // this class is not meant to be instantiated by client code
        private EmployeeMetadata() { }
        
#pragma warning disable 0169

        public int EmployeeID;

        public string LastName;

        public string FirstName;

        public string Title;

        public string TitleOfCourtesy;

        public Nullable<System.DateTime> BirthDate;

        public Nullable<System.DateTime> HireDate;

        public string Address;

        public string City;

        public string Region;

        public string PostalCode;

        public string Country;

        public string HomePhone;

        public string Extension;

        public byte[] Photo;

        public string Notes;

        public Nullable<int> ReportsTo;

        public string PhotoPath;

#pragma warning restore 0169
    }
}
