//------------------------------------------------------------------------------
// <autogenerated>
//   This file was generated by T4 code generator NTierDemoModel_NTierEntityGenerator.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using NTier.Common.Domain.Model;
using NTier.Server.Domain.Repositories;
using NTierDemo.Common.Domain.Model.NTierDemo;

namespace NTierDemo.Server.Domain.Repositories
{
    public partial class NTierDemoRepository : NTier.Server.Domain.Repositories.EntityFramework.Repository, INTierDemoRepository
    {
        #region Constructors

        public NTierDemoRepository()
            : base("name=NTierDemoEntities", "NTierDemoEntities")
        {
        }

        public NTierDemoRepository(string connectionString, string containerName = "NTierDemoEntities")
            : base(connectionString, containerName)
        {
        }

        public NTierDemoRepository(EntityConnection connection, string containerName = "NTierDemoEntities")
            : base(connection, containerName)
        {
        }

        #endregion Constructors

        #region EntitySets

        public IEntitySet<User> Users
        {
            get { return _users  ?? (_users = CreateEntitySet<User>("Users")); }
        }
        private IEntitySet<User> _users;

        public IEntitySet<Blog> Blogs
        {
            get { return _blogs  ?? (_blogs = CreateEntitySet<Blog>("Blogs")); }
        }
        private IEntitySet<Blog> _blogs;

        public IEntitySet<Post> Posts
        {
            get { return _posts  ?? (_posts = CreateEntitySet<Post>("Posts")); }
        }
        private IEntitySet<Post> _posts;

        #endregion EntitySets
    }
}
