//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Northwind.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using IntegrationTest.Common.Domain.Model.Northwind;
using NTier.Client.Domain;

namespace IntegrationTest.Client.Domain
{
    public partial interface INorthwindChangeSetFactory
    {
        NorthwindChangeSet CreateChangeSet(IEnumerable<Category> categories, IEnumerable<DemographicGroup> demographicGroups, IEnumerable<Customer> customers, IEnumerable<DynamicContentEntity> dynamicContentEntities, IEnumerable<Employee> employees, IEnumerable<Order_Detail> order_Details, IEnumerable<Order> orders, IEnumerable<Product> products, IEnumerable<Region> regions, IEnumerable<Shipper> shippers, IEnumerable<Supplier> suppliers, IEnumerable<Territory> territories);
    }
}
