//------------------------------------------------------------------------------
// <autogenerated>
//   This file was generated by T4 code generator NTierDemoModel_NTierEntityGenerator.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace NTierDemo.Common.Domain.Model.NTierDemo
{
    [DataContract(IsReference = true)]
    public sealed partial class NTierDemoResultSet : NTierDemoChangeSet, IResultSet
    {
        #region ctor
        public NTierDemoResultSet(NTierDemoChangeSet changeSet)
            : base(changeSet)
        {
        }
        #endregion

        #region DataMember

        [DataMember]
        public IList<User> UserConcurrencyConflicts { get; private set; }

        [DataMember]
        public IList<Blog> BlogConcurrencyConflicts { get; private set; }

        [DataMember]
        public IList<Post> PostConcurrencyConflicts { get; private set; }

        #endregion

        #region AddConcurrencyConflicts

        public void AddConcurrencyConflicts(IEnumerable<Entity> entities)
        {
            foreach (var entity in entities)
            {
                if (entity is User)
                {
                    AddConcurrencyConflict((User)entity);
                }
                else if (entity is Blog)
                {
                    AddConcurrencyConflict((Blog)entity);
                }
                else if (entity is Post)
                {
                    AddConcurrencyConflict((Post)entity);
                }
                else
                {
                    throw new Exception(string.Format("Unknown type {0}", entity.GetType().Name));
                }
            }
        }

        private void AddConcurrencyConflict(User entity)
        {
            if (UserConcurrencyConflicts == null)
            {
                UserConcurrencyConflicts = new List<User>();
            }
            UserConcurrencyConflicts.Add(entity);
        }

        private void AddConcurrencyConflict(Blog entity)
        {
            if (BlogConcurrencyConflicts == null)
            {
                BlogConcurrencyConflicts = new List<Blog>();
            }
            BlogConcurrencyConflicts.Add(entity);
        }

        private void AddConcurrencyConflict(Post entity)
        {
            if (PostConcurrencyConflicts == null)
            {
                PostConcurrencyConflicts = new List<Post>();
            }
            PostConcurrencyConflicts.Add(entity);
        }

        #endregion

        #region IsConcurrencyConflict

        public bool IsConcurrencyConflict(User e)
        {
            return UserConcurrencyConflicts != null && UserConcurrencyConflicts.Count > 0 && UserConcurrencyConflicts.Contains(e);
        }

        public bool IsConcurrencyConflict(Blog e)
        {
            return BlogConcurrencyConflicts != null && BlogConcurrencyConflicts.Count > 0 && BlogConcurrencyConflicts.Contains(e);
        }

        public bool IsConcurrencyConflict(Post e)
        {
            return PostConcurrencyConflicts != null && PostConcurrencyConflicts.Count > 0 && PostConcurrencyConflicts.Contains(e);
        }

        #endregion

        #region HasConcurrencyConflicts
        public bool HasConcurrencyConflicts
        {
            get
            {
                return UserConcurrencyConflicts != null ||
                    BlogConcurrencyConflicts != null ||
                    PostConcurrencyConflicts != null;
            }
        }
        #endregion
    }
}
