//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator NTierDemoModel_NTierEntityGenerator.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace NTierDemo.Common.Domain.Model.NTierDemo
{
    [DataContract(IsReference = true)]
    public sealed partial class NTierDemoResultSet : NTierDemoChangeSet, IResultSet
    {
        public NTierDemoResultSet(NTierDemoChangeSet changeSet)
            : base(changeSet)
        {
        }
    }
}
