//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator NTierDemoModel_NTierEntityGenerator.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace NTierDemo.Common.Domain.Model.NTierDemo
{
    [DataContract(IsReference = true)]
    public partial class NTierDemoChangeSet : IChangeSet
    {
        public NTierDemoChangeSet()
        {
        }

        protected NTierDemoChangeSet(NTierDemoChangeSet changeSet)
        {
            this.Users = changeSet.Users;
            this.Blogs = changeSet.Blogs;
            this.Posts = changeSet.Posts;
        }

        [DataMember]
        public List<User> Users { get; set; }

        [DataMember]
        public List<Blog> Blogs { get; set; }

        [DataMember]
        public List<Post> Posts { get; set; }

        public bool IsEmpty
        {
            get
            {
                return (ReferenceEquals(null, Users) || Users.Count == 0)
                    && (ReferenceEquals(null, Blogs) || Blogs.Count == 0)
                    && (ReferenceEquals(null, Posts) || Posts.Count == 0);
            }
        }

        public IEnumerator<Entity> GetEnumerator()
        {
            if (Users != null && Users.Count > 0)
            {
                foreach (var item in Users)
                {
                    yield return item;
                }
            }

            if (Blogs != null && Blogs.Count > 0)
            {
                foreach (var item in Blogs)
                {
                    yield return item;
                }
            }

            if (Posts != null && Posts.Count > 0)
            {
                foreach (var item in Posts)
                {
                    yield return item;
                }
            }

        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
