//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Northwind.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using IntegrationTest.Common.Domain.Model.Northwind;
using NTier.Common.Domain.Model;
using NTier.Server.Domain.Repositories;

namespace IntegrationTest.Server.Domain.Repositories
{
    public partial interface INorthwindRepository : IRepository
    {
        #region EntitySets

        IEntitySet<Category> Categories { get; }

        IEntitySet<DemographicGroup> DemographicGroups { get; }

        IEntitySet<Customer> Customers { get; }

        IEntitySet<DynamicContentEntity> DynamicContentEntities { get; }

        IEntitySet<Employee> Employees { get; }

        IEntitySet<Order_Detail> Order_Details { get; }

        IEntitySet<Order> Orders { get; }

        IEntitySet<Product> Products { get; }

        IEntitySet<Region> Regions { get; }

        IEntitySet<Shipper> Shippers { get; }

        IEntitySet<Supplier> Suppliers { get; }

        IEntitySet<Territory> Territories { get; }

        #endregion EntitySets
    }
}
