//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator NTierDemoModel_NTierEntityGenerator.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using NTier.Client.Domain;
using NTierDemo.Common.Domain.Model.NTierDemo;

namespace NTierDemo.Client.Domain
{
    public partial interface INTierDemoChangeSetFactory
    {
        NTierDemoChangeSet CreateChangeSet(IEnumerable<User> users, IEnumerable<Blog> blogs, IEnumerable<Post> posts);
    }
}
