//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator ProductModel.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using NTier.Common.Domain.Model;
using NTier.Server.Domain.Repositories;
using ProductManager.Common.Domain.Model.ProductManager;

namespace ProductManager.Server.Domain.Repositories
{
    public partial interface IProductManagerRepository : IRepository
    {
        #region EntitySets

        IEntitySet<Product> Products { get; }

        IEntitySet<ProductCategory> ProductCategories { get; }

        #endregion EntitySets
    }
}
