//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcurrencyDemo.Server.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARecord
    {
        public long Id { get; set; }
        public string Value { get; set; }
        public System.Guid Key { get; set; }
        public System.DateTime ChangedDate { get; set; }
    }
}
