//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator SimpleParentChildModel.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using NTier.Client.Domain;
using Test.Common.Domain.Model.SimpleParentChild;

namespace Test.Client.Domain
{
    public partial interface ISimpleParentChildChangeSetFactory
    {
        SimpleParentChildChangeSet CreateChangeSet(IEnumerable<Parent> parentSet, IEnumerable<Child> childSet);
    }
}
