//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Model2.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace TableInheritance.Common.Domain.Model.TableInheritanceDemoDB
{
    [Serializable]
    [DataContract(IsReference = true)]
    public partial class Customer : Person, INotifyPropertyChanged, INotifyPropertyChanging, IDataErrorInfo
    {
        #region Constructor and Initialization

        // partial method for initialization
        partial void Initialize();

        public Customer()
        {
            Initialize();
        }

        #endregion Constructor and Initialization

        #region Simple Properties

        [DataMember]
        [Required]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [SimpleProperty]
        public global::System.Int32 CustomerStatus
        {
            get { return _customerStatus; }
            set
            {
                if (_customerStatus != value)
                {
                    CustomerStatusChanging(value);
                    OnPropertyChanging("CustomerStatus", value);
                    var previousValue = _customerStatus;
                    _customerStatus = value;
                    OnPropertyChanged("CustomerStatus", previousValue, value);
                    CustomerStatusChanged(previousValue);
                }
            }
        }
        private global::System.Int32 _customerStatus;

        partial void CustomerStatusChanging(global::System.Int32 newValue);
        partial void CustomerStatusChanged(global::System.Int32 previousValue);

        #endregion Simple Properties

        #region Complex Properties

        #endregion Complex Properties

        #region Navigation Properties

        #endregion Navigation Properties

        #region ChangeTracking

        protected override void ClearNavigationProperties()
        {
            base.ClearNavigationProperties();
        }

        #endregion ChangeTracking

        #region Association Fixup

        #endregion Association Fixup
    }
}
