//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Model2.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace TableInheritance.Common.Domain.Model.TableInheritanceDemoDB
{
    [Serializable]
    [DataContract(IsReference = true)]
    public partial class Employee : Person, INotifyPropertyChanged, INotifyPropertyChanging, IDataErrorInfo
    {
        #region Constructor and Initialization

        // partial method for initialization
        partial void Initialize();

        public Employee()
        {
            Initialize();
        }

        #endregion Constructor and Initialization

        #region Simple Properties

        [DataMember]
        [Required]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [ServerGeneration(ServerGenerationTypes.Insert | ServerGenerationTypes.Update)]
        [SimpleProperty]
        public global::System.DateTime EntryDate
        {
            get { return _entryDate; }
            set
            {
                if (_entryDate != value)
                {
                    EntryDateChanging(value);
                    OnPropertyChanging("EntryDate", value);
                    var previousValue = _entryDate;
                    _entryDate = value;
                    OnPropertyChanged("EntryDate", previousValue, value);
                    EntryDateChanged(previousValue);
                }
            }
        }
        private global::System.DateTime _entryDate;

        partial void EntryDateChanging(global::System.DateTime newValue);
        partial void EntryDateChanged(global::System.DateTime previousValue);

        #endregion Simple Properties

        #region Complex Properties

        #endregion Complex Properties

        #region Navigation Properties

        #endregion Navigation Properties

        #region ChangeTracking

        protected override void ClearNavigationProperties()
        {
            base.ClearNavigationProperties();
        }

        #endregion ChangeTracking

        #region Association Fixup

        #endregion Association Fixup
    }
}
