//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Model2.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace TableInheritance.Common.Domain.Model.TableInheritanceDemoDB
{
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(Customer))]
    [KnownType(typeof(Employee))]
    [KnownType(typeof(Address))]
    public abstract partial class Person : Entity, INotifyPropertyChanged, INotifyPropertyChanging, IDataErrorInfo
    {
        #region Constructor and Initialization

        // partial method for initialization
        partial void Initialize();

        public Person()
        {
            Initialize();
        }

        #endregion Constructor and Initialization

        #region Simple Properties

        [DataMember]
        [Key]
        [Required]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [ServerGeneration(ServerGenerationTypes.Insert)]
        [SimpleProperty]
        public global::System.Int64 Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (!IsDeserializing && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    IdChanging(value);
                    OnPropertyChanging("Id", value);
                    var previousValue = _id;
                    _id = value;
                    OnPropertyChanged("Id", previousValue, value);
                    IdChanged(previousValue);
                }
            }
        }
        private global::System.Int64 _id;

        partial void IdChanging(global::System.Int64 newValue);
        partial void IdChanged(global::System.Int64 previousValue);

        [DataMember]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [SimpleProperty]
        public global::System.String FirstName
        {
            get { return _firstName; }
            set
            {
                if (_firstName != value)
                {
                    FirstNameChanging(value);
                    OnPropertyChanging("FirstName", value);
                    var previousValue = _firstName;
                    _firstName = value;
                    OnPropertyChanged("FirstName", previousValue, value);
                    FirstNameChanged(previousValue);
                }
            }
        }
        private global::System.String _firstName;

        partial void FirstNameChanging(global::System.String newValue);
        partial void FirstNameChanged(global::System.String previousValue);

        [DataMember]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [SimpleProperty]
        public global::System.String LastName
        {
            get { return _lastName; }
            set
            {
                if (_lastName != value)
                {
                    LastNameChanging(value);
                    OnPropertyChanging("LastName", value);
                    var previousValue = _lastName;
                    _lastName = value;
                    OnPropertyChanged("LastName", previousValue, value);
                    LastNameChanged(previousValue);
                }
            }
        }
        private global::System.String _lastName;

        partial void LastNameChanging(global::System.String newValue);
        partial void LastNameChanged(global::System.String previousValue);

        [DataMember]
#if !CLIENT_PROFILE
        [RoundtripOriginal]
#endif
        [ForeignKeyProperty]
        [SimpleProperty]
        public Nullable<global::System.Int64> HomeAddressId
        {
            get { return _homeAddressId; }
            set
            {
                if (_homeAddressId != value)
                {
                    HomeAddressIdChanging(value);
                    OnPropertyChanging("HomeAddressId", value);
                    if (!IsDeserializing)
                    {
                        if (Address1 != null && Address1.Id != value)
                        {
                            Address1 = null;
                        }
                    }
                    var previousValue = _homeAddressId;
                    _homeAddressId = value;
                    OnPropertyChanged("HomeAddressId", previousValue, value);
                    HomeAddressIdChanged(previousValue);
                }
            }
        }
        private Nullable<global::System.Int64> _homeAddressId;

        partial void HomeAddressIdChanging(Nullable<global::System.Int64> newValue);
        partial void HomeAddressIdChanged(Nullable<global::System.Int64> previousValue);

        #endregion Simple Properties

        #region Complex Properties

        #endregion Complex Properties

        #region Navigation Properties

        [DataMember]
        [NavigationProperty]
        public Address Address1
        {
            get { return _address1; }
            set
            {
                if (!ReferenceEquals(_address1, value))
                {
                    Address1Changing(value);
                    OnPropertyChanging("Address1", value);
                    var previousValue = _address1;
                    _address1 = value;
                    FixupAddress1(previousValue);
                    OnPropertyChanged("Address1", previousValue, value, isNavigationProperty: true);
                    Address1Changed(previousValue);
                }
            }
        }
        private Address _address1;

        partial void Address1Changing(Address newValue);
        partial void Address1Changed(Address previousValue);

        #endregion Navigation Properties

        #region ChangeTracking

        protected override void ClearNavigationProperties()
        {
            Address1 = null;
        }

        #endregion ChangeTracking

        #region Association Fixup

        private void FixupAddress1(Address previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }

            if (previousValue != null && previousValue.People.Contains(this))
            {
                previousValue.People.Remove(this);
            }

            if (Address1 != null)
            {
                if (!Address1.People.Contains(this))
                {
                    Address1.People.Add(this);
                }

                HomeAddressId = Address1.Id;
            }
            else if (!skipKeys)
            {
                HomeAddressId = null;
            }

            if (ChangeTracker.IsChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Address1")
                    && ReferenceEquals(ChangeTracker.OriginalValues["Address1"], Address1))
                {
                    //ChangeTracker.OriginalValues.Remove("Address1");
                }
                else
                {
                    //RecordOriginalValue("Address1", previousValue);
                }
                if (Address1 != null && !Address1.ChangeTracker.IsChangeTrackingEnabled)
                {
                    Address1.StartTracking();
                }
            }
        }

        #endregion Association Fixup

        protected override bool IsKeyEqual(Entity other)
        {
            var entity = other as Person;
            if (ReferenceEquals(null, entity)) return false;
            return this.Id == entity.Id;
        }

        protected override int GetKeyHashCode()
        {
            return this.Id.GetHashCode();
        }
    }
}
