//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Model2.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Globalization;
using System.Reflection;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace TableInheritance.Common.Domain.Model.TableInheritanceDemoDB
{
    [DataContract(IsReference = true)]
    public partial class TableInheritanceDemoDBChangeSet : IChangeSet
    {
        #region Constructor

        public TableInheritanceDemoDBChangeSet(IEnumerable<Person> people)
        {
            // retrieve changes sets (modified entities)
            var personChangeSet = people.GetChangeSet();

            // reduce entities (copy changed values)
            var peopleMap = personChangeSet.ReduceToModifications();
            if (peopleMap.Count > 0) this.People = peopleMap.Select(e => e.Item2).ToList();
        }

        protected TableInheritanceDemoDBChangeSet(TableInheritanceDemoDBChangeSet changeSet)
        {
            this.People = changeSet.People;
        }

        #endregion Constructor

        #region DataMember

        [DataMember]
        public List<Person> People { get; private set; }

        #endregion DataMember

        #region IsEmpty

        public bool IsEmpty
        {
            get
            {
                return People == null;
            }
        }

        #endregion IsEmpty

        #region IEnumerable

        public IEnumerator<Entity> GetEnumerator()
        {
            if (People != null && People.Count > 0)
            {
                foreach (var item in People)
                {
                    yield return item;
                }
            }

        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        #endregion IEnumerable
    }
}
