//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Model2.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using NTier.Common.Domain.Model;

namespace TableInheritance.Common.Domain.Model.TableInheritanceDemoDB
{
    [Serializable]
    [DataContract]
    [KnownType("GetKnownTypes")]
    public partial class TableInheritanceDemoDBOptimisticConcurrencyFault : NTier.Common.Domain.OptimisticConcurrencyFault
    {
        public TableInheritanceDemoDBOptimisticConcurrencyFault(string message, IEnumerable<Entity> entities)
            : base(message, entities)
        {
        }

        private static Type[] GetKnownTypes()
        {
            var types = typeof(TableInheritanceDemoDBOptimisticConcurrencyFault).Assembly.GetTypes()
                .Where(x => x.Namespace == typeof(TableInheritanceDemoDBOptimisticConcurrencyFault).Namespace)
                .Where(x => typeof(Entity).IsAssignableFrom(x) )
                .Where(x => x.IsPublic)
                .Where(x => !x.IsAbstract)
                .ToArray();
            return types;
        }
    }
}
