//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableInheritance.Server.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : Person
    {
        public Customer()
        {
            this.Demographics = new HashSet<Demographic>();
        }
    
        public int CustomerStatus { get; set; }
        public Nullable<long> DefaultShipmentAddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Demographic Demographic { get; set; }
        public virtual ICollection<Demographic> Demographics { get; set; }
    }
}
