//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableInheritance.Server.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demographic
    {
        public Demographic()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public long Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
