//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableInheritance.Server.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRole
    {
        public EmployeeRole()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
