//------------------------------------------------------------------------------
// <autogenerated>
//   This file was originally generated by T4 code generator ProductModel.tt. 
//   This file is meant to be edited manually and modifications do not get lost on regeneration. 
//   In case you want this file to be deleted or regenerated you have to remove (e.g. delete or rename) the existing version manually.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using NTier.Common.Domain.Model;

namespace ProductManager.Common.Domain.Model.ProductManager
{
    [MetadataType(typeof(ProductCategoryMetadata))]
    public partial class ProductCategory
    {
    }
    
    // This class allows you to attach custom attributes to properties of the ProductCategory class.
    //
    // For example, the following marks the Xyz property as a
    // required property and specifies the format for valid values:
    //    [Required]
    //    [RegularExpression("[A-Z][A-Za-z0-9]*")]
    //    [StringLength(32)]
    //    string Xyz;
    public sealed class ProductCategoryMetadata
    {
        // this class is not meant to be instantiated by client code
        private ProductCategoryMetadata() { }
        
#pragma warning disable 0169

        public int ProductCategoryID;

        [Display(AutoGenerateField = false)]
        public Nullable<int> ParentProductCategoryID;

        [StringLength(50)]
        public string Name;

        [Display(AutoGenerateField = false)]
        [ServerGeneration(ServerGenerationTypes.Insert)]
        public System.Guid rowguid;

        [Display(AutoGenerateField = false)]
        [ServerGeneration(ServerGenerationTypes.Insert | ServerGenerationTypes.Update)]
        public System.DateTime ModifiedDate;

#pragma warning restore 0169
    }
}
