//------------------------------------------------------------------------------
// <autogenerated>
//   This file was generated by T4 code generator NorthwindModel.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Objects;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Security.Permissions;
using System.ServiceModel;
using System.ServiceModel.Activation;
using System.Transactions;
using IntegrationTest.Common.Domain.Model.Northwind;
using IntegrationTest.Common.Domain.Service.Contracts;
using IntegrationTest.Server.Domain.Repositories;
using NTier.Common.Domain.Model;
using NTier.Server.Domain.Repositories;
using NTier.Server.Domain.Service;


namespace IntegrationTest.Server.Domain.Service
{
    [ServiceBehavior(TransactionAutoCompleteOnSessionClose = true)]
    public partial class NorthwindDataService : DataService<INorthwindRepository>, INorthwindDataService
    {
        #region repository factory

        partial void CreateRepository(ClientInfo clientInfo, ref INorthwindRepository repository);

        /// <summary>
        /// Creates a and returns a new instance of the repository
        /// </summary>
        /// <returns>A new instance of the repository</returns>
        protected override INorthwindRepository CreateRepository(ClientInfo clientInfo)
        {
            INorthwindRepository repository = null;

            CreateRepository(clientInfo, ref repository);

            return repository ?? new NorthwindRepository();
        }

        #endregion repository factory

        #region query service methods

        partial void PreProcessing(ClientInfo clientInfo, ref Query query, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Category> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Employee> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Order> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Product> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Region> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Shipper> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Supplier> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Territory> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<DemographicGroup> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<Customer> result, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, Query query, ref QueryResult<DynamicContentEntity> result, INorthwindRepository repository);

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Category> GetCategories(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Categories, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Employee> GetEmployees(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Employees, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Order> GetOrders(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Orders, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Product> GetProducts(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Products, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Region> GetRegions(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Regions, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Shipper> GetShippers(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Shippers, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Supplier> GetSuppliers(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Suppliers, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Territory> GetTerritories(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Territories, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<DemographicGroup> GetCustomerDemographics(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.CustomerDemographics, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<Customer> GetCustomers(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.Customers, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        [OperationBehavior(Impersonation = ImpersonationOption.Allowed)]
        public QueryResult<DynamicContentEntity> GetDynamicContentEntities(ClientInfo clientInfo, Query query)
        {
            using (var dataRepository = CreateRepository(clientInfo))
            {
                PreProcessing(clientInfo, ref query, dataRepository);
                var result = Get(dataRepository.DynamicContentEntities, query, clientInfo);
                PostProcessing(clientInfo, query, ref result, dataRepository);
                return result;
            }
        }

        #endregion query service methods

        #region update service method

        partial void PreProcessing(ClientInfo clientInfo, ref NorthwindChangeSet changeSet, INorthwindRepository repository);
        partial void BeforeSaving(ClientInfo clientInfo, ref NorthwindChangeSet changeSet, INorthwindRepository repository);
        partial void PostProcessing(ClientInfo clientInfo, ref NorthwindResultSet result, INorthwindRepository repository);

        [OperationBehavior(TransactionScopeRequired = true, Impersonation = ImpersonationOption.Allowed)]
        public NorthwindResultSet SubmitChanges(ClientInfo clientInfo, NorthwindChangeSet changeSet)
        {
            var resultSet = new NorthwindResultSet(changeSet);
            OnTransactionInit();
            try
            {
                using (var dataRepository = CreateRepository(clientInfo))
                {
                    // optional custom processing
                    PreProcessing(clientInfo, ref changeSet, dataRepository);

                    // apply chnages to repository
                    ApplyChanges(dataRepository, dataRepository.Categories, changeSet, changeSet.Categories, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Employees, changeSet, changeSet.Employees, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.OrderDetails, changeSet, changeSet.OrderDetails, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Orders, changeSet, changeSet.Orders, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Products, changeSet, changeSet.Products, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Regions, changeSet, changeSet.Regions, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Shippers, changeSet, changeSet.Shippers, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Suppliers, changeSet, changeSet.Suppliers, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Territories, changeSet, changeSet.Territories, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.CustomerDemographics, changeSet, changeSet.CustomerDemographics, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.Customers, changeSet, changeSet.Customers, clientInfo);
                    ApplyChanges(dataRepository, dataRepository.DynamicContentEntities, changeSet, changeSet.DynamicContentEntities, clientInfo);

                    // optional custom processing
                    BeforeSaving(clientInfo, ref changeSet, dataRepository);

                    // save changes
                    SaveChanges(dataRepository, changeSet, resultSet);

                    // optional custom processing
                    PostProcessing(clientInfo, ref resultSet, dataRepository);
                }
            }
            catch
            {
                if (Transaction.Current != null && Transaction.Current.TransactionInformation.Status == TransactionStatus.Active)
                {
                    Transaction.Current.Rollback();
                }
                throw;
            }
            finally
            {
                OnTransactionEnd();
            }
            return resultSet;
        }

        #endregion update service method
    }
}

