//------------------------------------------------------------------------------
// <auto-generated>
//   This file was generated by T4 code generator Model2.tt.
//   Any changes made to this file manually may cause incorrect behavior
//   and will be lost next time the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using NTier.Client.Domain;
using TableInheritance.Common.Domain.Model.TableInheritanceDemoDB;

namespace TableInheritance.Client.Domain
{
    public partial interface ITableInheritanceDemoDBChangeSetFactory
    {
        TableInheritanceDemoDBChangeSet CreateChangeSet(IEnumerable<Person> people, IEnumerable<Address> addresses, IEnumerable<Demographic> demographics, IEnumerable<EmployeeRole> employeeRoles);
    }
}
